docker_auth: &docker_auth
  auth:
    username: $DOCKER_USERNAME
    password: $DOCKER_PASSWORD

workspace: &workspace
  at: ~/scriptjar

slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:1.0.0
      <<: *docker_auth

work_directory: &work_directory
  working_directory: ~/scriptjar

resource_class: &resource_class
  resource_class: small

parameters:
  repo_name:
    type: string
    default: "scriptjar"

executors:
  jdk-executor:
    docker:
      - image: cimg/openjdk:11.0
        <<: *docker_auth
    <<: *resource_class
    <<: *work_directory
  machine-executor:
    machine:
      image: ubuntu-2204:2023.04.2
    resource_class: medium
    <<: *work_directory
  arm-executor:
    machine:
      image: ubuntu-2004:2022.04.1
    resource_class: arm.medium
    <<: *work_directory

version: 2.1
jobs:
  publish:
    executor: jdk-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=${CIRCLE_SHA1:0:8}
          GROOVY_VERSION=3.0.9-jre11
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker buildx create --name rockbuilder \
            --driver docker-container --use --bootstrap
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --build-arg GROOVY_VERSION=$GROOVY_VERSION \
            -t devatherock/scriptjar:$TAG \
            -t devatherock/scriptjar:latest \
            -f docker/Dockerfile .

  dockerhub_readme:
    docker:
      - image: peterevans/dockerhub-description:3.4.2
        <<: *docker_auth
    <<: *resource_class
    <<: *work_directory
    environment:
      DOCKERHUB_REPOSITORY: 'devatherock/<< pipeline.parameters.repo_name >>'
      SHORT_DESCRIPTION: 'CI plugin to convert Groovy scripts to executable jars'
      README_FILEPATH: README.md
    steps:
      - checkout
      - attach_workspace:
          <<: *workspace
      - run: |
          sh /entrypoint.sh

  functional_test:
    parameters:
      runner:
        type: executor
    executor: << parameters.runner >>
    steps:
      - checkout
      - attach_workspace:
          <<: *workspace
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: |
          make test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  publish_release:
    executor: jdk-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=${CIRCLE_TAG#v}
          DEV_TAG=${CIRCLE_SHA1:0:8}
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker buildx create --name rockbuilder \
            --driver docker-container --use --bootstrap
          docker buildx imagetools create \
            -t devatherock/scriptjar:$TAG devatherock/scriptjar:$DEV_TAG

  fast_functional_test:
    executor: arm-executor
    steps:
      - checkout
      - attach_workspace:
          <<: *workspace
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: |
          make docker-build test skip_pull=true

  notify:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#33ad7f"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack

workflows:
  version: 2.1
  docker_publish:
    jobs:
      - publish:
          context:
            - docker-credentials
          filters:
            branches:
              only: master
      - dockerhub_readme:
          context:
            - docker-credentials
            - dockerhub-readme-credentials
          requires:
            - publish
      - functional_test:
          name: functional_test_amd
          context:
            - docker-credentials
          runner: machine-executor
          requires:
            - publish
      - functional_test:
          name: functional_test_arm
          context:
            - docker-credentials
          runner: arm-executor
          requires:
            - dockerhub_readme
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - functional_test_amd
            - functional_test_arm

  release:
    jobs:
      - publish_release:
          context:
            - docker-credentials
          filters:
            branches:
              only: non-existent-branch
            tags:
              only: /^v[0-9\.]+$/
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - publish_release

  pr_check:
    jobs:
      - fast_functional_test:
          context:
            - docker-credentials
          filters:
            branches:
              ignore: master
