slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.7.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

work_directory: &work_directory
  working_directory: ~/scriptjar

resource_class: &resource_class
  resource_class: small
  
executors:
  jdk-executor:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory  

version: 2.1
jobs:
  publish:
    executor: jdk-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=${CIRCLE_SHA1:0:8}
          GROOVY_VERSION=3.0.9-jre11
          docker build --build-arg GROOVY_VERSION=$GROOVY_VERSION -t devatherock/drone-groovy-script-to-jar:$TAG -f docker/Dockerfile .
          docker tag devatherock/drone-groovy-script-to-jar:$TAG devatherock/drone-groovy-script-to-jar:latest
          docker tag devatherock/drone-groovy-script-to-jar:$TAG devatherock/vela-groovy-script-to-jar:$TAG
          docker tag devatherock/drone-groovy-script-to-jar:$TAG devatherock/vela-groovy-script-to-jar:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/drone-groovy-script-to-jar:$TAG
          docker push devatherock/drone-groovy-script-to-jar:latest
          docker push devatherock/vela-groovy-script-to-jar:$TAG
          docker push devatherock/vela-groovy-script-to-jar:latest
          
  functional_test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - attach_workspace:
          at: ~/scriptjar
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: |
          ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}          
  publish_release:
    executor: jdk-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=${CIRCLE_TAG#v}
          DEV_TAG=${CIRCLE_SHA1:0:8}
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker pull devatherock/drone-groovy-script-to-jar:$DEV_TAG
          docker tag devatherock/drone-groovy-script-to-jar:$DEV_TAG devatherock/drone-groovy-script-to-jar:$TAG
          docker tag devatherock/drone-groovy-script-to-jar:$TAG devatherock/vela-groovy-script-to-jar:$TAG
          docker push devatherock/drone-groovy-script-to-jar:$TAG
          docker push devatherock/vela-groovy-script-to-jar:$TAG        

  docker_build_dry_run:
    executor: jdk-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --build-arg GROOVY_VERSION=3.0.9-jre11 -f docker/Dockerfile .

  notify:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#33ad7f"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack

workflows:
  version: 2.1
  docker_publish:
    jobs:
      - publish:
          context:
            - docker-credentials
          filters:
            branches:
              only: master
      - functional_test:
          context:
            - docker-credentials
          requires:
            - publish
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - functional_test
  release:
    jobs:
      - publish_release:
          context:
            - docker-credentials
          filters:
            branches:
              only: non-existent-branch
            tags:
              only: /^v[0-9\.]+$/
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - publish_release          
  pr_check:
    jobs:
      - docker_build_dry_run:
          context:
            - docker-credentials
          filters:
            branches:
              ignore: master