if [ ! -z "$PLUGIN_SCRIPT_PATH" ]; then
  SCRIPT_PATH=$PLUGIN_SCRIPT_PATH
elif [ ! -z "$PARAMETER_SCRIPT_PATH" ]; then
  SCRIPT_PATH=$PARAMETER_SCRIPT_PATH
fi

if [ ! -z "$PLUGIN_OUTPUT_FILE" ]; then
  OUTPUT_FILE=$PLUGIN_OUTPUT_FILE
elif [ ! -z "$PARAMETER_OUTPUT_FILE" ]; then
  OUTPUT_FILE=$PARAMETER_OUTPUT_FILE
fi

if [ ! -z "$PLUGIN_STATIC_COMPILE" ]; then
  STATIC_COMPILE=$PLUGIN_STATIC_COMPILE
elif [ ! -z "$PARAMETER_STATIC_COMPILE" ]; then
  STATIC_COMPILE=$PARAMETER_STATIC_COMPILE
fi

if [ ! -z "$PLUGIN_NO_SIBLINGS" ]; then
  NO_SIBLINGS=$PLUGIN_NO_SIBLINGS
elif [ ! -z "$PARAMETER_NO_SIBLINGS" ]; then
  NO_SIBLINGS=$PARAMETER_NO_SIBLINGS
fi


if [ ! -z "$SCRIPT_PATH" ]; then
   ALL_OPTS="$ALL_OPTS -i $SCRIPT_PATH"
fi

if [ "$STATIC_COMPILE" = "true" ]; then
   ALL_OPTS="$ALL_OPTS -s"
fi

if [ "$NO_SIBLINGS" = "true" ]; then
   ALL_OPTS="$ALL_OPTS -n"
fi

if [ ! -z "$OUTPUT_FILE" ]; then
   ALL_OPTS="$ALL_OPTS -o $OUTPUT_FILE"
fi

groovy /scripts/scriptjar.groovy $ALL_OPTS